print("'abc-def'.isalpha(): ", 'abc-def'.isalpha())
print("'abc_def'.isalpha(): ", 'abc_def'.isalpha())
print("'abc def'.isalpha(): ", 'abc def'.isalpha())
print("'abc def'.isalpha( and 'abc def'.isspace()): ", 'abc def'.isalpha() and 'abc def'.isspace())
print("'abc def'.isalpha( or 'abc def'.isspace()): ", 'abc def'.isalpha() or 'abc def'.isspace())
print("'abcdef'.isalpha(): ", 'abcdef'.isalpha())
print("'31415'.isdigit(): ", '31415'.isdigit())
print("'-31415'.isdigit(): ", '-31415'.isdigit())
print("'31_415'.isdigit(): ", '31_415'.isdigit())
print("'31.415'.isdigit(): ", '31.415'.isdigit())
print("''.isspace(): ", ''.isspace())
