# config.ym

  welcome: "Welcome to the calculator program!  Enter your name:"

  valid_name: "Make sure to use a valid name"

  enter_nums: "Enter 2 numbers"

  val_num: "Hmm.. that doesn't look ike a valid number"

  val_op: "Must choose 1, 2, 3, or 4"

  again: "Do you want to perform another calculation? (Y to calculate again)"

  bye: "Thank you for using the calculator.  Goodbye!"
